FROM alpine:3.10

VOLUME /etc/ssl/certs
WORKDIR /etc/ssl/certs

ENV APK_MIRROR="https://mirrors.tuna.tsinghua.edu.cn/alpine"

RUN echo -e "${APK_MIRROR}/v3.10/main\n${APK_MIRROR}/v3.10/community\n" > /etc/apk/repositories \
    && apk update \
    && apk add --no-cache openssl

CMD openssl dhparam -out ./dhparam.tmp.pem 4096 \
  && mv -f ./dhparam.tmp.pem ./dhparam.pem
